services:
  adguardhome:
    image: adguard/adguardhome:v0.107.56
    container_name: adguardhome
    labels:
      - wud.tag.include=^v\d+\.\d+\.\d+$$
    restart: unless-stopped
    networks:
      - root_proxmox-docker-vnet
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/adguardhome/work:/opt/adguardhome/work
      - /home/adguardhome/conf:/opt/adguardhome/conf

networks:
  root_proxmox-docker-vnet:
    external: true