---
- Administración:
    - Proxmox:
        icon: proxmox.svg
        href: https://proxmox.dgarrido.net
        description: Servidor de virtualización
        widget:
          type: proxmox
          url: https://proxmox.dgarrido.net
          username: "{{HOMEPAGE_VAR_PROXMOX_USERNAME}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_PASSWORD}}"

    - Zoraxy:
        icon: zoraxy.svg
        href: https://proxy.dgarrido.net
        description: Servidor Proxy

    - Adguard Home:
        icon: adguard-home.svg
        href: https://dns.dgarrido.net
        description: Servidor DNS
        widget:
          type: adguard
          url: https://dns.dgarrido.net
          username: "{{HOMEPAGE_VAR_ADGUARD_USERNAME}}"
          password: "{{HOMEPAGE_VAR_ADGUARD_PASSWORD}}"

    - Uptime Kuma:
        icon: uptime-kuma.svg
        href: https://monitor.dgarrido.net
        description: Monitorización de servicios
        widget:
            type: uptimekuma
            url: https://monitor.dgarrido.net
            slug: statuspageslug
    
    - What's Up Docker:
        icon: whats-up-docker.svg
        href: https://whatsupdocker.dgarrido.net
        descripción: Versión de los contenedores
        widget:
          type: whatsupdocker
          url: https://whatsupdocker.dgarrido.net
          # username: "{{HOMEPAGE_VAR_WHATSUPDOCKER_USERNAME}}"
          # password: "{{HOMEPAGE_VAR_WHATSUPDOCKER_PASSWORD}}"

    - Download Station:
        icon: synology-download-station.webp
        href: https://synology.dgarrido.net
        description: Cliente Torrent
        winget:
          type: downloadstation
          url: https://synology.dgarrido.net
          username: "{{HOMEPAGE_VAR_SYNOLOGY_DOWNLOADSTATION_USERNAME}}"
          password: "{{HOMEPAGE_VAR_SYNOLOGY_DOWNLOADSTATION_PASSWORD}}"

- Streaming:
  - Web:
    - Jellyfin:
        icon: jellyfin.svg
        href: https://streaming.dgarrido.net
        description: Plataforma de visionado
        widget:
          type: jellyfin
          url: https://streaming.dgarrido.net
          fields: ["movies", "series", "episodes"]
          key: "{{HOMEPAGE_VAR_JELLYFIN_KEY}}"
          enableBlocks: true
          enableUser: true
          showEpisodeNumber: true

    - Jellyseerr:
        icon: jellyseerr.svg
        href: https://requests.dgarrido.net
        description: Plataforma de solicitud
        widget:
          type: jellyseerr
          url: https://requests.dgarrido.net
          key: "{{HOMEPAGE_VAR_JELLYSEERR_KEY}}"
  - Engine:
    - Prowlarr:
        icon: prowlarr.svg
        href: https://prowlarr.dgarrido.net
        description: Indexador de contenido
        widget:
          type: prowlarr
          url: https://prowlarr.dgarrido.net
          key: "{{HOMEPAGE_VAR_PROWLARR_KEY}}"

    - Radarr:
        icon: radarr.svg
        href: https://radarr.dgarrido.net
        description: Gestión de películas
        widget:
          type: radarr
          url: https://radarr.dgarrido.net
          key: "{{HOMEPAGE_VAR_RADARR_KEY}}"

    - Sonarr:
        icon: sonarr.svg
        href: https://sonarr.dgarrido.net
        description: Gestión de series
        widget:
          type: sonarr
          url: https://sonarr.dgarrido.net
          key: "{{HOMEPAGE_VAR_SONARR_KEY}}"

  - Calendar: 
    - Calendar:
        widget:
          type: calendar
          view: monthly
          showTime: true
          timezone: Europe/Madrid
          integrations:
            - type: sonarr
              service_group: Engine
              service_name: Sonarr
                
            - type: radarr
              service_group: Engine
              service_name: Radarr
