---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

language: es

title: Homelab

# providers:
#   openweathermap: openweathermapapikey
#   weatherapi: weatherapiapikey

layout:
  Streaming:
    style: row
    columns: 3
    Web:
      header: false
    Engine:
      header: false
    Calendar:
      header: false