services:
  jellyseerr:
    image: fallenbagel/jellyseerr:2.3.0
    container_name: jellyseerr
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
    networks:
      - root_proxmox-docker-vnet
    dns:
      - 172.20.0.100
    volumes:
      - /home/jellyseerr/config:/app/config

networks:
  root_proxmox-docker-vnet:
    external: true